import Head from 'next/head'
import { Container } from '@/components/container'
import { Box, Center, Flex } from '@chakra-ui/react'
import { Header } from '@/components/header'
import { Search } from '@/features/landing/search'
import { Footer } from '@/components/footer'

export default function About() {
  return (
    <>
      <Head>
        <title>All-In Theater</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box margin='0 auto' width='100%'>
        <Box position='relative' height='100%'>
          <Flex justifyContent='space-between'>
            <Header />
            <Search 
              top={{base: '', md: '0'}}
              right={{base: '', md: '0'}}
              marginTop={{ base: '', md: '41px' }}
              marginRight={{base: '', md: '55px'}}
              marginLeft='auto'
            />
          </Flex>
        </Box>
        <Footer />
      </Box>
    </>
  )
}
