import Head from 'next/head'
import { Container } from '@/components/container'
import { Box, Button, Center, Flex, HStack, VStack, Text, RadioGroup, Stack, Radio, Input, Textarea, Checkbox } from '@chakra-ui/react'
import { Header } from '@/components/header'
import { Search } from '@/features/landing/search'
import { Footer } from '@/components/footer'

export default function Contact() {

  const RequiredTag = () => (
    <Center
      borderRadius='full'
      fontSize='10px'
      background='transparent linear-gradient(90deg, #934B77 0%, #813131 100%) 0% 0% no-repeat padding-box;'
      width={'48px'}
      height={'18px'}
    >
      必須
    </Center>
  )

  return (
    <>
      <Head>
        <title>All-In Theater</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box margin='0 auto' width='100%' position='relative'>
        <Box position='relative' height='100%'>
          <Flex justifyContent='space-between'>
            <Header 
              withTextOnSp={false} 
              left={{ base: '14px', md: '38px'}}
              right={'unset'}
            />
            <Search 
              top={{base: '33px', md: '0'}}
              right={{base: '23px', md: '0'}}
              marginTop={{ base: '33px', md: '41px' }}
              marginRight={{base: '23px', md: '55px'}}
              marginLeft='auto'
            />
          </Flex>
        </Box>
        <Container 
          marginTop={{base: '120px', md: '140px'}}
          paddingLeft={{base: '0', md: '132px'}}
          paddingRight={{base: '0', md: '128px'}}
          _after={{
            position: 'absolute',
            top: 0,
            right: 0,
            content: "''",
            width: '7px',
            height: '100%',
            background: '#707070'
          }}
        >
          <Center
            fontSize={{base: '25px', md: '28px'}}
            lineHeight={{base: '43px', md: '44px'}}
          >
            お問い合わせ
          </Center>
          <Center width='100%'>
            <Box
              width='100%'
              borderRadius='17px'
              padding={{base: '62px 25px', md: '100px 120px'}}
              background={'transparent linear-gradient(180deg, #000 0%, #222222 100%) 0% 0% no-repeat padding-box'}
            >
              <VStack spacing='20px' alignItems='flex-start'>
                <Text fontSize={{base: '12px', md: '14px'}}>
                  種別
                </Text>
                <RadioGroup>
                  <Stack 
                    direction={{base: 'column', md: 'row'}} 
                    spacing={{ base: '14px', md: '26px'}}
                    fontSize={{ base: '14px', mg: '16px'}}
                  >
                    <Radio>
                    求人を掲載したい
                    </Radio>
                    <Radio>
                    お問い合わせ
                    </Radio>
                  </Stack>
                </RadioGroup>
              </VStack>
              <VStack 
                marginTop={{base: '42px', md: '50px'}} 
                alignItems='flex-start' 
                spacing={{ base: '44px', md: '52px'}}
              >
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                      会社・組織名
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Input 
                    placeholder='会社名・組織名'
                    _placeholder={{
                      color: 'black',
                      opacity: 0.2
                    }}
                    fontSize={'16px'}
                    width='100%'
                    height={'50px'}
                    background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                  />
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                      部署名・部門名
                    </Text>
                  </HStack>
                  <Input 
                    placeholder='会社名・組織名'
                    _placeholder={{
                      color: 'black',
                      opacity: 0.2
                    }}
                    fontSize={'16px'}
                    width='100%'
                    height={'50px'}
                    background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                  />
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    氏名(漢字)
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Flex gridGap='24px' width='100%'>
                    <Input 
                      placeholder='田中'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                    <Input 
                      placeholder='太郎'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </Flex>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    氏名(ふりがな)
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Flex gridGap='24px' width='100%'>
                    <Input 
                      placeholder='たなか'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                    <Input 
                      placeholder='たろう'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </Flex>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    メールアドレス
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Input 
                    placeholder='メールアドレス'
                    _placeholder={{
                      color: 'black',
                      opacity: 0.2
                    }}
                    fontSize={'16px'}
                    width='100%'
                    height={'50px'}
                    background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                  />
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    問い合わせ内容
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Textarea 
                    placeholder='テキストを入力してください'
                    _placeholder={{
                      color: 'black',
                      opacity: 0.2
                    }}
                    fontSize={'16px'}
                    padding={'17px 26px'}
                    resize='none'
                    width='100%'
                    minHeight={{base: '100px', md: '147px'}}
                    height={'50px'}
                    background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                  />
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    個人情報の取り扱いについて
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Checkbox>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    個人情報保護に関する事項に同意して先に進む
                    </Text>
                  </Checkbox>
                </VStack>
                <Center width='100%'>
                  <Button
                    width={{base: '286px', md: '314px'}}
                    height={{base: '48px', md: '52px'}}
                    borderRadius='full'
                    fontSize={{base: '16px', md: '20px'}}
                  >
                    入力を確認する
                  </Button>
                </Center>
              </VStack>
            </Box>
          </Center>
        </Container>
        <Footer />
      </Box>
    </>
  )
}
