import { useState } from 'react'
import axios from 'axios'
import { useForm } from "react-hook-form"
import Head from 'next/head'
import { Container } from '@/components/container'
import { Box, Button, Center, Flex, HStack, VStack, Text, RadioGroup, Stack, Radio, Input, Textarea, Checkbox } from '@chakra-ui/react'
import { Header } from '@/components/header'
import { Search } from '@/features/landing/search'
import { Footer } from '@/components/footer'
import { WP_REST_API } from '@/constants'

export default function Contact() {
  const [isAgree, setIsAgree] = useState(false)
  const [inquiry_type, setInquiryType] = useState('inquiry')
  const [formData, setFormData] = useState({})
  const [forConfirm, setForConfirm] = useState(false)
  const [confirmed, setConfirmed] = useState(false)
  const [done, setDone] = useState(false)
  const [loading, setLoading] = useState(false)
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm({
    defaultValues: {
      company_name: '',
      department_name: '',
      familyname_kanji: '',
      givenname_kanji: '',
      familyname_furigana: '',
      givenname_furigana: '',
      email: '',
      inquiry: ''
    }
  })

  const validateEmail = () => {
    return /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]+$/i
  }

  const submitForm = (_formData) => {
    setForConfirm(true)
    setConfirmed(false)
    setFormData({
      ..._formData,
      inquiry_type: inquiry_type === 'inquiry' ? 'お問い合わせ' : '求人を掲載したい',
      name: `${_formData?.familyname_furigana}${_formData?.givenname_furigana}`,
      name_kanji: `${_formData?.familyname_kanji}${_formData?.givenname_kanji}`,
      name_furigana: `${_formData?.familyname_furigana}${_formData?.givenname_furigana}`
    })
  }

  const handleConfirm = () => {
    setConfirmed(true)
    sendInquiry()
  }

  const sendInquiry = async () => {
    setLoading(true)
    try {
      let response = await axios.post(`${WP_REST_API}/wp-json/api/inquiry`, formData)
      setLoading(false)
      if(response?.data?.success) {
        setDone(true)
        setFormData({})
        setInquiryType('inquiry')
        setIsAgree(false)
        setForConfirm(false)
        setConfirmed(false)
        reset()
      }
    } catch (error) {
      console.log('error', error)
      setLoading(false)
    }
  }

  const RequiredTag = () => (
    <Center
      borderRadius='full'
      fontSize='10px'
      background='transparent linear-gradient(90deg, #934B77 0%, #813131 100%) 0% 0% no-repeat padding-box;'
      width={'48px'}
      height={'18px'}
    >
      必須
    </Center>
  )

  const RenderFormField = ({ formKey, children }) => {
    if(forConfirm) {
      return <Text fontSize={'16px'}>{formData[formKey]}</Text>
    }

    return children
  }

  return (
    <>
      <Head>
        <title>All-In Theater</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box margin='0 auto' width='100%' position='relative'>
        <Box position='relative' height='100%'>
          <Flex justifyContent='space-between'>
            <Header 
              withTextOnSp={false} 
              left={{ base: '14px', md: '38px'}}
              right={'unset'}
            />
            <Search 
              top={{base: '33px', md: '0'}}
              right={{base: '23px', md: '0'}}
              marginTop={{ base: '33px', md: '41px' }}
              marginRight={{base: '23px', md: '55px'}}
              marginLeft='auto'
            />
          </Flex>
        </Box>
        <Container 
          marginTop={{base: '120px', md: '140px'}}
          paddingLeft={{base: '0', md: '132px'}}
          paddingRight={{base: '0', md: '128px'}}
          _after={{
            position: 'absolute',
            top: 0,
            right: 0,
            content: "''",
            width: '7px',
            height: '100%',
            background: '#707070'
          }}
        >
          <Center
            fontSize={{base: '25px', md: '28px'}}
            lineHeight={{base: '43px', md: '44px'}}
          >
            お問い合わせ
          </Center>
          <Center width='100%'>
            {done && (
              <Box
                width='100%'
                borderRadius='17px'
                padding={{base: '62px 25px', md: '100px 120px'}}
                background={'transparent linear-gradient(180deg, #000 0%, #222222 100%) 0% 0% no-repeat padding-box'}
              >
                <VStack spacing='30px'>
                  <Text fontSize='30px'>送信完了</Text>
                  <Button
                    onClick={() => {
                      setDone(false)
                    }}
                    width={{base: '286px', md: '314px'}}
                    height={{base: '48px', md: '52px'}}
                    borderRadius='full'
                    fontSize={{base: '16px', md: '20px'}}
                  >
                    戻る
                  </Button>
                </VStack>
              </Box>
            )}
            <Box
              display={done ? 'none' : 'block'}
              width='100%'
              borderRadius='17px'
              padding={{base: '62px 25px', md: '100px 120px'}}
              background={'transparent linear-gradient(180deg, #000 0%, #222222 100%) 0% 0% no-repeat padding-box'}
            >
              <VStack spacing='20px' alignItems='flex-start'>
                <Text fontSize={{base: '12px', md: '14px'}}>
                  種別
                </Text>
                <RenderFormField formKey={'inquiry_type'}>
                  <RadioGroup
                    value={inquiry_type}
                    onChange={setInquiryType}
                  >
                    <Stack 
                      direction={{base: 'column', md: 'row'}} 
                      spacing={{ base: '14px', md: '26px'}}
                      fontSize={{ base: '14px', mg: '16px'}}
                    >
                      <Radio value='post_a_job'>
                      求人を掲載したい
                      </Radio>
                      <Radio value='inquiry'>
                      お問い合わせ
                      </Radio>
                    </Stack>
                  </RadioGroup>
                </RenderFormField>
              </VStack>
              <VStack 
                marginTop={{base: '42px', md: '50px'}} 
                alignItems='flex-start' 
                spacing={{ base: '44px', md: '52px'}}
              >
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                      会社・組織名
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <RenderFormField formKey={'company_name'}>
                    <Input 
                      {...register('company_name', { required: true })}
                      isInvalid={!!errors?.company_name}
                      placeholder='会社名・組織名'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      color='black'
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </RenderFormField>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                      部署名・部門名
                    </Text>
                  </HStack>
                  <RenderFormField formKey={'department_name'}>
                    <Input 
                      {...register('department_name')}
                      placeholder='会社名・組織名'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      color='black'
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </RenderFormField>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    氏名(漢字)
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Flex gridGap='24px' width='100%'>
                    <RenderFormField formKey={'familyname_kanji'}>
                      <Input 
                        {...register('familyname_kanji', { required: true })}
                        isInvalid={!!errors?.familyname_kanji}
                        placeholder='田中'
                        _placeholder={{
                          color: 'black',
                          opacity: 0.2
                        }}
                        color='black'
                        fontSize={'16px'}
                        width='100%'
                        height={'50px'}
                        background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                      />
                    </RenderFormField>
                    <RenderFormField formKey={'givenname_kanji'}>
                      <Input 
                        {...register('givenname_kanji', { required: true })}
                        isInvalid={!!errors?.givenname_kanji}
                        placeholder='太郎'
                        _placeholder={{
                          color: 'black',
                          opacity: 0.2
                        }}
                        color='black'
                        fontSize={'16px'}
                        width='100%'
                        height={'50px'}
                        background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                      />
                    </RenderFormField>
                  </Flex>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    氏名(ふりがな)
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <Flex gridGap='24px' width='100%'>
                    <RenderFormField formKey={'familyname_furigana'}>
                      <Input 
                        {...register('familyname_furigana', { required: true })}
                        isInvalid={!!errors?.familyname_furigana}
                        placeholder='たなか'
                        _placeholder={{
                          color: 'black',
                          opacity: 0.2
                        }}
                        color='black'
                        fontSize={'16px'}
                        width='100%'
                        height={'50px'}
                        background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                      />
                    </RenderFormField>
                    <RenderFormField formKey={'givenname_furigana'}>
                      <Input 
                        {...register('givenname_furigana', { required: true })}
                        isInvalid={!!errors?.givenname_furigana}
                        placeholder='たろう'
                        _placeholder={{
                          color: 'black',
                          opacity: 0.2
                        }}
                        color='black'
                        fontSize={'16px'}
                        width='100%'
                        height={'50px'}
                        background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                      />
                    </RenderFormField>
                    
                  </Flex>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    メールアドレス
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <RenderFormField formKey={'email'}>
                    <Input 
                      {...register('email', { 
                        validate: {
                          required: (val) => {
                            let notEmpty = val?.trim().length > 0
                            return notEmpty
                          },
                        },
                        pattern: {
                          value: validateEmail(),
                          message: '有効なメールアドレスを入力してください。',
                        },
                      })}
                      isInvalid={!!errors?.email}
                      placeholder='メールアドレス'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      color='black'
                      fontSize={'16px'}
                      width='100%'
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </RenderFormField>
                </VStack>
                <VStack alignItems='flex-start' width='100%' spacing='14px'>
                  <HStack spacing='16px'>
                    <Text fontSize={{ base: '12px', md: '14px'}}>
                    問い合わせ内容
                    </Text>
                    <RequiredTag />
                  </HStack>
                  <RenderFormField formKey={'inquiry'}>
                    <Textarea 
                      {...register('inquiry', { required: true })}
                      isInvalid={!!errors?.inquiry}
                      placeholder='テキストを入力してください'
                      _placeholder={{
                        color: 'black',
                        opacity: 0.2
                      }}
                      color='black'
                      fontSize={'16px'}
                      padding={'17px 26px'}
                      resize='none'
                      width='100%'
                      minHeight={{base: '100px', md: '147px'}}
                      height={'50px'}
                      background='transparent linear-gradient(270deg, #D6DCE0 0%, #B7B7B7 73%, #C5BEC6 100%) 0% 0% no-repeat padding-box'
                    />
                  </RenderFormField>
                </VStack>
                {(!forConfirm && !confirmed) && 
                  <VStack alignItems='flex-start' width='100%' spacing='14px'>
                    <HStack spacing='16px'>
                      <Text fontSize={{ base: '12px', md: '14px'}}>
                      個人情報の取り扱いについて
                      </Text>
                      <RequiredTag />
                    </HStack>
                    <Checkbox isChecked={isAgree} onChange={(e) => setIsAgree(e.target.checked)}>
                      <Text fontSize={{ base: '12px', md: '14px'}}>
                      個人情報保護に関する事項に同意して先に進む
                      </Text>
                    </Checkbox>
                  </VStack>
                }
                <Center width='100%'>
                  <Button
                    isLoading={loading}
                    isDisabled={!isAgree}
                    onClick={() => {
                      if(!forConfirm && !confirmed) {
                        handleSubmit(submitForm)()
                      } else {
                        handleConfirm()
                      }
                    }}
                    width={{base: '286px', md: '314px'}}
                    height={{base: '48px', md: '52px'}}
                    borderRadius='full'
                    fontSize={{base: '16px', md: '20px'}}
                  >
                    {(!forConfirm && !confirmed) ? '送信' : (
                      (forConfirm ? '入力を確認する' : '')
                    )}
                  </Button>
                </Center>
              </VStack>
            </Box>
          </Center>
        </Container>
        <Footer />
      </Box>
    </>
  )
}
