import axios from 'axios'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { isReservedKeyword } from '@/utils'
import { format } from 'date-fns'
import Head from 'next/head'
import { Container } from '@/components/container'
import { Box, Button, Center, Flex, HStack, Icon, Text } from '@chakra-ui/react'
import { Header } from '@/components/header'
import { Search } from '@/features/landing/search'
import { Footer } from '@/components/footer'
import { FacebookIcon2 } from '@/components/icons/FacebookIcon2'
import { TwitterIcon } from '@/components/icons/TwitterIcon'
import { LineIcon } from '@/components/icons/LineIcon'
import { BIcon } from '@/components/icons/BIcon'
import { ChevronLeftIcon, ChevronRightIcon } from '@chakra-ui/icons'
import { Recommended } from '@/features/landing/recommended'
import { WP_REST_API } from '@/constants'

export default function ArticleDetail() {
  const router = useRouter()
  const [article, setArticle] = useState(null)
  const [tags, setTagList] = useState([])

  useEffect(() => {
    axios
      .get(`${WP_REST_API}/wp-json/wp/v2/tags?per_page=12`)
      .then((response) => {
        if(response?.data?.length > 0) {
          setTagList(response.data)
        }
      }).catch((err) => {
        console.log('err', err)
      })
  }, [])

  useEffect(() => {
    axios
      .get(`${WP_REST_API}/wp-json/wp/v2/articles?slug=${router?.query?.slug}`)
      .then((response) => {
        if(response?.data?.length > 0) {
          setArticle(response.data[0])
        }
      }).catch((err) => {
        console.log('err', err)
      })
  }, [router?.query?.slug])

  const renderSnsIcons = () => (
    <Flex gridGap='17px'>
      <Icon as={TwitterIcon} />
      <Icon as={FacebookIcon2} />
      <Icon as={LineIcon} />
      <Icon as={BIcon} />
    </Flex>
  )

  return (
    <>
      <Head>
        <title>All-In Theater</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box margin='0 auto' width='100%'>
        <Box position='relative' height='100%'>
          <Flex justifyContent='space-between'>
            <Header />
            <Search 
              top={{base: '', md: '0'}}
              right={{base: '', md: '0'}}
              marginTop={{ base: '', md: '41px' }}
              marginRight={{base: '', md: '55px'}}
              marginLeft='auto'
            />
          </Flex>
        </Box>
        <Container 
          paddingLeft={{base: '20px', md: '132px'}}
          paddingRight={{base: '', md: '128px'}}
          _after={{
            position: 'absolute',
            top: 0,
            right: 0,
            content: "''",
            width: '7px',
            height: '100%',
            background: '#707070'
          }}
        >
          <Box width='100%'>
            <Box 
              marginTop={{base: '', md: '112px'}}
              fontSize={{base: '', md: '28px'}}
              dangerouslySetInnerHTML={{
                __html: article?.excerpt?.rendered || article?.post_excerpt
              }}
            />
            <Text
              textAlign='left'
              fontSize={{base: '', md: '15px'}}
              my={{base: '', md: '30px'}}
            >
              {(article?.post_date || article?.date) && format(new Date(article?.post_date || article?.date), 'yyyy.MM.dd')}
            </Text>
            <Flex
              width='100%'
              alignItems='center'
              justifyContent='space-between'
              mb={{base: '', md: '80px'}}
            >
              <Flex gridGap='10px' flexWrap='wrap'>
                {article?.article_tags?.map((tag) => {
                  if(isReservedKeyword(tag?.slug)) return null 
                  return (
                    <Center
                      key={`tag-${tag?.term_id}`}
                      height={{base: '28px', md: '30px'}}
                      px={'18px'}
                      fontSize={{base: '12px', md: '14px'}}
                      background='#123E43'
                      color='#39A5B2'
                      borderRadius='full'
                    >
                      #{tag?.name}
                    </Center>
                  )
                })}
              </Flex>
              {renderSnsIcons()}
            </Flex>
            <Center mb={{base: '', md: '63px'}}>
              <Button
                width={{base: '', md: '274px'}}
                height={{base: '', md: '46px'}}
                fontSize={{base: '', md: '14px'}}
                fontWeight='normal'
                border='1px solid white'
                borderRadius='full'
                bg='transparent'
                color='white'
              >
              アニメーションを見る
              </Button>
            </Center>
            <Center width='100%'>
              <Box 
                dangerouslySetInnerHTML={{
                  __html: article?.content?.rendered || article?.post_content
                }}
              />
            </Center>
          </Box>
        </Container>
        <Box 
          mt={{base: '', md: '136px'}}
          width='100%'
          height={{base: '', md: '245px'}}
          bg='black'
          backdropFilter='blur(15px)'
          position='relative'
        >
          <Box
            fontSize={{base: '', md: '141px'}}
            lineHeight={{base: '', md: '171px'}}
            letterSpacing='8.46px'
            fontWeight='bold'
            textAlign='center'
            color='white'
            opacity='0.1'
          >
            JOB OFFER
          </Box>
          <Center
            position='absolute'
            top='0'
            left='0'
            width='100%'
            flexDirection='column'
            height={{base: '', md: '245px'}}
          >
            <Text
              fontSize={{base: '', md: '44px'}}
              letterSpacing='2.2px'
              color='white'
              fontWeight='normal'
            >
            この求人に応募する
            </Text>
            <Flex marginTop={{base: '', md: '43px'}} gridGap={{base: '', md: '36px'}}>
              <Button
                width={{base: '', md: '258px'}}
                height={{base: '', md: '46px'}}
                borderRadius='full'
              >
              採用ページへ
              </Button>
              <Button
                width={{base: '', md: '258px'}}
                height={{base: '', md: '46px'}}
                borderRadius='full'
              >
              メールで応募する
              </Button>
            </Flex>
          </Center>
        </Box>
        <Center 
          mt={{base: '', md: '77px'}}
          mb={{base: '', md: '113px'}}
        >
          {renderSnsIcons()}
        </Center>
        <Container>
          <Center width='100%' justifyContent='space-between' px={{base: '', md: '100px', lg: '150px'}}>
            <Button
              bg='transparent'
              color='white'
              fontSize={{base: '', md: '16px'}}
              fontWeight='normal'
              _hover={{
                bg: 'transparent'
              }}
            >
              <ChevronLeftIcon fontSize='40px' />
              <Text>
              BEFORE　会社と出会う
              </Text>
            </Button>
            <Button
              bg='transparent'
              color='white'
              fontSize={{base: '', md: '16px'}}
              fontWeight='normal'
              _hover={{
                bg: 'transparent'
              }}
            >
              <Text>
              ALL STORYへ
              </Text>
            </Button>
            <Button
              bg='transparent'
              color='white'
              fontSize={{base: '', md: '16px'}}
              fontWeight='normal'
              _hover={{
                bg: 'transparent'
              }}
            >
              <Text>
              AFTER　会社と出会う
              </Text>
              <ChevronRightIcon fontSize='40px' />
            </Button>
          </Center>
        </Container>
        <Container 
          marginTop={{base: '', md: '150px'}}
          paddingLeft={{base: '16px', md: '132px'}}
          paddingRight={{base: '16px', md: '128px'}}
        >
          <Recommended />
        </Container>
        <Box
          position='relative'
          marginTop={{base: '', md: '152px'}}
          py={'60px'}
          background='transparent linear-gradient(0deg, #000 0%, #414141 100%) 0% 0% no-repeat padding-box'
        >
          <Center
            position='absolute'
            top='-16px'
            width='100%'
          >
            <Center
              borderRadius='full'
              background='#717171'
              width={{base: '', md: '170px'}}
              height={{base: '', md: '32px'}}
              fontSize={{base: '', md: '15px'}}
              fontWeight='normal'
            >
              別の気分で探す
            </Center>
          </Center>
          <Center width='100%'>
            <HStack 
              spacing='20px'
              justifyContent='center'
              width='60%'
              flexWrap='wrap'
            >
              {tags?.map((tag,i) => {
                if(isReservedKeyword(tag?.slug)) return null 
                return (
                  <Center
                    key={`tag-${i}`}
                    height={{base: '28px', md: '38px'}}
                    px={'18px'}
                    fontSize={{base: '12px', md: '14px'}}
                    color='white'
                    borderRadius='full'
                    border='1px solid white'
                  >
                    #{tag?.name}
                  </Center>
                )
              })}
            </HStack>
          </Center>
        </Box>
        <Footer />
      </Box>
    </>
  )
}
